### ISSUE TITLE
Missing ../images/wave-drawer.png

### ISSUE THREAD

**Issue by MonsieurLanza** [skiant/mastodon-light-theme#11]
Got    ```bash
 ERROR in ./node_modules/css-loader?{"minimize":true}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js!./app/javascript/styles/mastodon_light.scss
    Module not found: Error: Can't resolve '../images/wave-drawer.png' in '/home/mastodon/live/app/javascript/styles'``` 

when trying to compile.

(Mastodon 2.2.0)

**Comment by TheHeroBilly** [comment]
Same issue, any way to fix?

**Comment by bremensaki** [comment]
Should be fixed by #13 but could use a test on a clean installation that's not my dev copy which is getting quite different from the base. I noticed this a while back but only just got a chance to poke at it.

**Comment by skiant** [comment]
Thanks @bremensaki I really had no time to look into it. The PR has been merged. I'll close this issue, feel free to reopen if it pops up again.
