### ISSUE TITLE
Fail to compile on v2.1.0rc2

### ISSUE THREAD

**Issue by renatolond** [skiant/mastodon-light-theme#8]
On v2.1.0.rc2 it fails to compile with `Undefined variable: "$cjk-langs".`
I managed to fix by adding `$cjk-langs: ja, ko, zh-CN, zh-HK, zh-TW;` from `app/javascript/styles/mastodon/variables.scss`, but I'm not sure if it's the only new variable.

**Comment by bremensaki** [comment]
Deployed theme on 2.1 final with this one line fix in place and it seems fine. Couldn't see any other new variables in place.

**Comment by skiant** [comment]
Pushed the fix in d5199e8eeb74db922d25c4205419573222ccab9e, let me know if there's any issue left.
